"""initial_schema

Revision ID: f0eb38df42a5
Revises: 
Create Date: 2026-06-13 05:19:27.717685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
try:
    from pgvector.sqlalchemy import Vector
except ImportError:
    Vector = None


# revision identifiers, used by Alembic.
revision: str = 'f0eb38df42a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('type', sa.Enum('SCHOLARSHIP', 'INTERNSHIP', 'FELLOWSHIP', 'HACKATHON', 'EXCHANGE', name='opportunitytype'), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_short', sa.String(length=500), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('funding_type', sa.Enum('FULLY_FUNDED', 'PARTIAL', 'UNPAID', 'STIPEND', name='fundingtype'), nullable=True),
    sa.Column('funding_amount', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('remote_eligible', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_id', sa.String(length=512), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding', Vector(1536) if Vector else sa.Text(), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opportunities_active_deadline', 'opportunities', ['is_active', 'deadline'], unique=False)
    op.create_index(op.f('ix_opportunities_content_hash'), 'opportunities', ['content_hash'], unique=True)
    op.create_index(op.f('ix_opportunities_deadline'), 'opportunities', ['deadline'], unique=False)
    op.create_index(op.f('ix_opportunities_is_active'), 'opportunities', ['is_active'], unique=False)
    op.create_index(op.f('ix_opportunities_type'), 'opportunities', ['type'], unique=False)
    op.create_index('ix_opportunities_type_deadline', 'opportunities', ['type', 'deadline'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('SAVED', 'APPLIED', 'UNDER_REVIEW', 'SHORTLISTED', 'OUTCOME', name='applicationstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requirements_checklist', sa.JSON(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_result', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_application_user_opportunity')
    )
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index('ix_applications_user_status', 'applications', ['user_id', 'status'], unique=False)
    op.create_table('eligibility',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('nationality', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('gpa_min', sa.Float(), nullable=True),
    sa.Column('gpa_scale', sa.Float(), nullable=True),
    sa.Column('enrollment_status', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('field_of_study', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('citizenship_required', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('raw_requirements', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    op.create_table('notification_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email_weekly_digest', sa.Boolean(), nullable=True),
    sa.Column('email_deadline_14d', sa.Boolean(), nullable=True),
    sa.Column('email_deadline_7d', sa.Boolean(), nullable=True),
    sa.Column('email_deadline_3d', sa.Boolean(), nullable=True),
    sa.Column('email_deadline_1d', sa.Boolean(), nullable=True),
    sa.Column('email_new_matches', sa.Boolean(), nullable=True),
    sa.Column('inapp_new_matches', sa.Boolean(), nullable=True),
    sa.Column('inapp_deadline_alerts', sa.Boolean(), nullable=True),
    sa.Column('digest_day_of_week', sa.Integer(), nullable=True),
    sa.Column('digest_hour_utc', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('citizenship', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('enrollment_status', sa.String(length=100), nullable=True),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('languages', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('interests', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('career_goals', sa.Text(), nullable=True),
    sa.Column('career_goal_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('gpa_scale', sa.Float(), nullable=True),
    sa.Column('resume_s3_key', sa.String(length=512), nullable=True),
    sa.Column('resume_parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resume_parse_confidence', sa.Float(), nullable=True),
    sa.Column('completeness_score', sa.Integer(), nullable=True),
    sa.Column('embedding', Vector(1536) if Vector else sa.Text(), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preference_weights', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('education',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('field', sa.String(length=255), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('gpa_scale', sa.Float(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Enum('WORK', 'VOLUNTEER', 'RESEARCH', name='experiencetype'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('skill_bonus', sa.Float(), nullable=True),
    sa.Column('recency_bonus', sa.Float(), nullable=True),
    sa.Column('location_bonus', sa.Float(), nullable=True),
    sa.Column('is_seen', sa.Boolean(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'opportunity_id', name='uq_match_student_opportunity')
    )
    op.create_index('ix_matches_student_score', 'matches', ['student_id', 'score'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('NEW_MATCH', 'DEADLINE_14D', 'DEADLINE_7D', 'DEADLINE_3D', 'DEADLINE_1D', 'STATUS_UPDATE', 'WEEKLY_DIGEST', 'PROFILE_PROMPT', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=2048), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_emailed', sa.Boolean(), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_matches_student_score', table_name='matches')
    op.drop_table('matches')
    op.drop_table('experience')
    op.drop_table('education')
    op.drop_table('student_profiles')
    op.drop_table('notification_settings')
    op.drop_table('eligibility')
    op.drop_index('ix_applications_user_status', table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_opportunities_type_deadline', table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_is_active'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_deadline'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_content_hash'), table_name='opportunities')
    op.drop_index('ix_opportunities_active_deadline', table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
